spring.application.name=profile-service
server.servlet.context-path=/api/profile

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=9020

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_HOST:http://localhost:8761/eureka/}

logging.level.org.springframework.web.client.RestTemplate=WARN
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
logging.level.org.springframewyesork.web.HttpLogging=WARN